// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsVaV1iPqvG6Na87xUkDZ_lXyA1VaZaIE',
    appId: '1:245096092615:web:906fd2d1517f9b6b6cbfe2',
    messagingSenderId: '245096092615',
    projectId: 'baatcheet-ae522',
    authDomain: 'baatcheet-ae522.firebaseapp.com',
    storageBucket: 'baatcheet-ae522.firebasestorage.app',
    measurementId: 'G-7H0H7J851N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFnHKekEyUvJasyq1T1WfEPE1LNR5Vsyc',
    appId: '1:245096092615:android:9f461764f9de7b5d6cbfe2',
    messagingSenderId: '245096092615',
    projectId: 'baatcheet-ae522',
    storageBucket: 'baatcheet-ae522.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsUipMUav8kg1TsF1J9KwX9xj7PwQ-hVI',
    appId: '1:245096092615:ios:4e3cac61260520a36cbfe2',
    messagingSenderId: '245096092615',
    projectId: 'baatcheet-ae522',
    storageBucket: 'baatcheet-ae522.firebasestorage.app',
    iosBundleId: 'com.example.baatcheet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsUipMUav8kg1TsF1J9KwX9xj7PwQ-hVI',
    appId: '1:245096092615:ios:4e3cac61260520a36cbfe2',
    messagingSenderId: '245096092615',
    projectId: 'baatcheet-ae522',
    storageBucket: 'baatcheet-ae522.firebasestorage.app',
    iosBundleId: 'com.example.baatcheet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsVaV1iPqvG6Na87xUkDZ_lXyA1VaZaIE',
    appId: '1:245096092615:web:fd0a1fc89ede2f626cbfe2',
    messagingSenderId: '245096092615',
    projectId: 'baatcheet-ae522',
    authDomain: 'baatcheet-ae522.firebaseapp.com',
    storageBucket: 'baatcheet-ae522.firebasestorage.app',
    measurementId: 'G-2R9Y8EZJ08',
  );
}
